name = "Breadcrumb"
description = "Displays the path to the current resource using a hierarchy of links."

[[examples]]
name = "Breadcrumb"

[[references]]
name = "Breadcrumb"
description = "Contains the contents of the breadcrumb."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol#attributes">ol</a> \
attributes."""
attrs = [
  { attr = "number_type", attr_type = "usize", default = "1", description = """Renamed <ol> \
    `type` attribute to avoid name collisions.""" },
]

[[references]]
name = "BreadcrumbItem"
description = "Contains the contents of the breadcrumb."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/li#attributes">li</a> \
attributes."""
attrs = []

[[references]]
name = "BreadcrumbSeparator"
description = "Contains the contents of the breadcrumb."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/li#attributes">li</a> \
attributes."""
attrs = []
