name = "Button"
description = "Displays a button."

[[examples]]
name = "Button"

[[examples]]
name = "Button Sizes"
title = "Button Sizes"

[[examples]]
name = "Button Icon"
title = "Button Icon"

[[examples]]
name = "Button With Icon"
title = "With Icon"

[[references]]
name = "Button"
description = "Creates a button."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button#attributes">button</a> \
attributes."""
attrs = [
  { attr = "button_type", attr_type = "String", default = """"submit"""", description = """Renamed <button> \
    `type` attribute to avoid name collisions.""" },
  { attr = "size", attr_type = "String", default = """""""", description = """Specify the size to \
    render the button.""" },
  { attr = "variant", attr_type = "String", default = """"primary"""", description = """Specify \
    the style of button to render.""" },
]
